export interface Word {
  word: string;
  hint: string;
  category: string;
}

export const CATEGORIES = {
  ANIMALS: 'Hayvanlar',
  FOODS: 'Yemekler',
  JOBS: 'Meslekler',
  CITIES: 'Şehirler',
  OBJECTS: 'Eşyalar',
  SPORTS: 'Spor',
  MOVIES: 'Film/Dizi',
  FRUITS: 'Meyveler',
  DRINKS: 'İçecekler',
  CLOTHES: 'Kıyafetler',
  TRANSPORT: 'Ulaşım',
  NATURE: 'Doğa',
  TECH: 'Teknoloji',
  MUSIC: 'Müzik',
  BODY: 'Vücut',
  COLORS: 'Renkler',
  NUMBERS: 'Sayılar',
  MONTHS: 'Aylar',
  SEASONS: 'Mevsimler',
  COUNTRIES: 'Ülkeler',
  SCIENCE: 'Bilim',
  ART: 'Sanat',
  LITERATURE: 'Edebiyat',
  HISTORY: 'Tarih',
  SCHOOL: 'Okul',
  HOME: 'Ev',
  WEATHER: 'Hava',
  FEELINGS: 'Duygular',
  ACTIONS: 'Eylemler',
} as const;

export type Category = typeof CATEGORIES[keyof typeof CATEGORIES];

export const WORDS: Word[] = [
  // === HAYVANLAR ===
  { word: "Aslan", hint: "Ormanların kralı", category: CATEGORIES.ANIMALS },
  { word: "Fil", hint: "Dünyanın en büyük karada yaşayan hayvanı", category: CATEGORIES.ANIMALS },
  { word: "Köpek", hint: "İnsanın en sadık dostu", category: CATEGORIES.ANIMALS },
  { word: "Kedi", hint: "Evlerde beslenen tüylü hayvan", category: CATEGORIES.ANIMALS },
  { word: "Penguen", hint: "Uçamayan kuş", category: CATEGORIES.ANIMALS },
  { word: "Kaplumbağa", hint: "Yavaş hareket eden sürüngen", category: CATEGORIES.ANIMALS },
  { word: "Yılan", hint: "Bacaksız sürüngen", category: CATEGORIES.ANIMALS },
  { word: "Kurbağa", hint: "Hem suda hem karada yaşayan", category: CATEGORIES.ANIMALS },
  { word: "Papağan", hint: "Konuşabilen kuş", category: CATEGORIES.ANIMALS },
  { word: "Arı", hint: "Bal yapan böcek", category: CATEGORIES.ANIMALS },
  { word: "Zürafa", hint: "Boynu en uzun hayvan", category: CATEGORIES.ANIMALS },
  { word: "Timsah", hint: "Nehirlerde yaşayan büyük sürüngen", category: CATEGORIES.ANIMALS },
  { word: "İnek", hint: "Süt veren hayvan", category: CATEGORIES.ANIMALS },
  { word: "At", hint: "Binilen hayvan", category: CATEGORIES.ANIMALS },
  { word: "Koyun", hint: "Yünü kullanılan hayvan", category: CATEGORIES.ANIMALS },
  { word: "Keçi", hint: "Tırmanan hayvan", category: CATEGORIES.ANIMALS },
  { word: "Tavuk", hint: "Yumurtlayan kümes hayvanı", category: CATEGORIES.ANIMALS },
  { word: "Horoz", hint: "Sabah şarkı söyleyen", category: CATEGORIES.ANIMALS },
  { word: "Ördek", hint: "Suyu seven kuş", category: CATEGORIES.ANIMALS },
  { word: "Kaz", hint: "Büyük su kuşu", category: CATEGORIES.ANIMALS },
  { word: "Balık", hint: "Suda yaşayan", category: CATEGORIES.ANIMALS },
  { word: "Köpekbalığı", hint: "Denizlerin kralı", category: CATEGORIES.ANIMALS },
  { word: "Yunus", hint: "Akıllı deniz memelisi", category: CATEGORIES.ANIMALS },
  { word: "Ahtapot", hint: "8 kollu deniz canlısı", category: CATEGORIES.ANIMALS },
  { word: "Karınca", hint: "Çalışkan böcek", category: CATEGORIES.ANIMALS },
  { word: "Arı", hint: "Bal yapan böcek", category: CATEGORIES.ANIMALS },
  { word: "Kelebek", hint: "Kanatlı böcek", category: CATEGORIES.ANIMALS },
  { word: "Sivrisinek", hint: "Kaşındırıcı böcek", category: CATEGORIES.ANIMALS },

  // === YEMEKLER ===
  { word: "Pizza", hint: "İtalyan mutfağından yuvarlak yemek", category: CATEGORIES.FOODS },
  { word: "Hamburger", hint: "Etli ekmek", category: CATEGORIES.FOODS },
  { word: "Kebap", hint: "Kömürde pişirilen et", category: CATEGORIES.FOODS },
  { word: "Makarna", hint: "İtalyan usulü hamur işi", category: CATEGORIES.FOODS },
  { word: "Döner", hint: "Dikey dönen et", category: CATEGORIES.FOODS },
  { word: "Lahmacun", hint: "İnce hamurlu etli yemek", category: CATEGORIES.FOODS },
  { word: "Mantı", hint: "Kıymalı küçük hamur", category: CATEGORIES.FOODS },
  { word: "Simit", hint: "Halkalı ekmek", category: CATEGORIES.FOODS },
  { word: "Börek", hint: "Kat kat hamur", category: CATEGORIES.FOODS },
  { word: "Köfte", hint: "Şekil verilmiş kıyma", category: CATEGORIES.FOODS },
  { word: "Tavuk", hint: "Kümes hayvanı", category: CATEGORIES.FOODS },
  { word: "Balık", hint: "Deniz ürünü", category: CATEGORIES.FOODS },
  { word: "Pilav", hint: "Taneli pirinç yemeği", category: CATEGORIES.FOODS },
  { word: "Çorba", hint: "Sulu yemek", category: CATEGORIES.FOODS },
  { word: "Salata", hint: "Sebzeli soğuk yemek", category: CATEGORIES.FOODS },
  { word: "Sandviç", hint: "Ekmek arası", category: CATEGORIES.FOODS },
  { word: "Tost", hint: "Erilmiş ekmek", category: CATEGORIES.FOODS },
  { word: "Kumpir", hint: "Soslu patates", category: CATEGORIES.FOODS },
  { word: "Sushi", hint: "Japon balık yemeği", category: CATEGORIES.FOODS },
  { word: "Pasta", hint: "Tatlı hamur işi", category: CATEGORIES.FOODS },
  { word: "Kek", hint: "Yağlı tatlı", category: CATEGORIES.FOODS },
  { word: "Bisküvi", hint: "Kuru tatlı", category: CATEGORIES.FOODS },
  { word: "Dondurma", hint: "Soğuk tatlı", category: CATEGORIES.FOODS },
  { word: "Çikolata", hint: "Kakao tatlısı", category: CATEGORIES.FOODS },
  { word: "Helva", hint: "Tahinli tatlı", category: CATEGORIES.FOODS },
  { word: "Baklava", hint: "Fıstıklı tatlı", category: CATEGORIES.FOODS },
  { word: "Lokum", hint: "Şekerli Türk tatlısı", category: CATEGORIES.FOODS },
  { word: "Şerbet", hint: "Tatlı içecek", category: CATEGORIES.FOODS },
  { word: "Meyve Suyu", hint: "Sıkılmış meyve", category: CATEGORIES.FOODS },

  // === MESLEKLER ===
  { word: "Doktor", hint: "Hastaları tedavi eden", category: CATEGORIES.JOBS },
  { word: "Öğretmen", hint: "Öğrencilere ders veren", category: CATEGORIES.JOBS },
  { word: "Mühendis", hint: "Proje tasarlayan", category: CATEGORIES.JOBS },
  { word: "Aşçı", hint: "Yemek yapan", category: CATEGORIES.JOBS },
  { word: "Avukat", hint: "Hukuki işleri takip eden", category: CATEGORIES.JOBS },
  { word: "Polis", hint: "Güvenliği sağlayan", category: CATEGORIES.JOBS },
  { word: "Asker", hint: "Ülkeyi savunan", category: CATEGORIES.JOBS },
  { word: "Pilot", hint: "Uçak kullanan", category: CATEGORIES.JOBS },
  { word: "Şoför", hint: "Araba kullanan", category: CATEGORIES.JOBS },
  { word: "Hemşire", hint: "Doktora yardım eden", category: CATEGORIES.JOBS },
  { word: "Mimar", hint: "Bina tasarlayan", category: CATEGORIES.JOBS },
  { word: "Sanatçı", hint: "Eser yaratan", category: CATEGORIES.JOBS },
  { word: "Yazar", hint: "Kitap yazan", category: CATEGORIES.JOBS },
  { word: "Şarkıcı", hint: "Şarkı söyleyen", category: CATEGORIES.JOBS },
  { word: "Oyuncu", hint: "Rol alan", category: CATEGORIES.JOBS },
  { word: "Fotoğrafçı", hint: "Resim çeken", category: CATEGORIES.JOBS },
  { word: "Berber", hint: "Saç kesen", category: CATEGORIES.JOBS },
  { word: "Kuaför", hint: "Güzellik yapan", category: CATEGORIES.JOBS },
  { word: "Temizlikçi", hint: "Temizlik yapan", category: CATEGORIES.JOBS },
  { word: "Çiftçi", hint: "Tarım yapan", category: CATEGORIES.JOBS },
  { word: "Balıkçı", hint: "Balık tutan", category: CATEGORIES.JOBS },
  { word: "Marangoz", hint: "Ahşap işleyen", category: CATEGORIES.JOBS },
  { word: "Demirci", hint: "Demir işleyen", category: CATEGORIES.JOBS },
  { word: "Terzi", hint: "Kıyafet diken", category: CATEGORIES.JOBS },
  { word: "Kasap", hint: "Et satan", category: CATEGORIES.JOBS },
  { word: "Fırıncı", hint: "Ekmek yapan", category: CATEGORIES.JOBS },
  { word: "Elektrikçi", hint: "Elektrik işleyen", category: CATEGORIES.JOBS },
  { word: "Plumbcı", hint: "Su tesisatçı", category: CATEGORIES.JOBS },
  { word: "Dişçi", hint: "Diş tedavi eden", category: CATEGORIES.JOBS },
  { word: "Eczacı", hint: "İlaç veren", category: CATEGORIES.JOBS },
  { word: "Psikolog", hint: "Ruhsal danışman", category: CATEGORIES.JOBS },
  { word: "Muhasebeci", hint: "Hesap işleyen", category: CATEGORIES.JOBS },
  { word: "Sekreter", hint: "Yazı işleyen", category: CATEGORIES.JOBS },
  { word: "Garson", hint: "Servis yapan", category: CATEGORIES.JOBS },

  // === ŞEHİRLER ===
  { word: "İstanbul", hint: "Türkiye'nin en büyük şehri", category: CATEGORIES.CITIES },
  { word: "Ankara", hint: "Türkiye'nin başkenti", category: CATEGORIES.CITIES },
  { word: "İzmir", hint: "Ege'nin incisi", category: CATEGORIES.CITIES },
  { word: "Antalya", hint: "Turizm başkenti", category: CATEGORIES.CITIES },
  { word: "Bursa", hint: "Yeşil şehir", category: CATEGORIES.CITIES },
  { word: "Trabzon", hint: "Karadeniz'in incisi", category: CATEGORIES.CITIES },
  { word: "Gaziantep", hint: "Gastronomi başkenti", category: CATEGORIES.CITIES },
  { word: "Konya", hint: "Selçuklu başkenti", category: CATEGORIES.CITIES },
  { word: "Adana", hint: "Kebap şehri", category: CATEGORIES.CITIES },
  { word: "Şanlıurfa", hint: "Peygamberler şehri", category: CATEGORIES.CITIES },
  { word: "Diyarbakır", hint: "Surlu şehir", category: CATEGORIES.CITIES },
  { word: "Mardin", hint: "Taş şehir", category: CATEGORIES.CITIES },
  { word: "Van", hint: "Gölü olan şehir", category: CATEGORIES.CITIES },
  { word: "Erzurum", hint: "Palandöken şehri", category: CATEGORIES.CITIES },
  { word: "Samsun", hint: "Karadeniz'in başkenti", category: CATEGORIES.CITIES },
  { word: "Eskişehir", hint: "Şeker şehri", category: CATEGORIES.CITIES },
  { word: "Kayseri", hint: "Manto şehri", category: CATEGORIES.CITIES },
  { word: "Sivas", hint: "Kangal köpeği", category: CATEGORIES.CITIES },
  { word: "Manisa", hint: "Mesir macunu", category: CATEGORIES.CITIES },
  { word: "Balıkesir", hint: "Zeytin şehri", category: CATEGORIES.CITIES },

  // === EŞYALAR ===
  { word: "Bilgisayar", hint: "Dijital cihaz", category: CATEGORIES.OBJECTS },
  { word: "Telefon", hint: "İletişim cihazı", category: CATEGORIES.OBJECTS },
  { word: "Televizyon", hint: "Görüntü izlenen cihaz", category: CATEGORIES.OBJECTS },
  { word: "Buzdolabı", hint: "Yiyecekleri soğutan cihaz", category: CATEGORIES.OBJECTS },
  { word: "Saat", hint: "Zamanı gösteren", category: CATEGORIES.OBJECTS },
  { word: "Gözlük", hint: "Görmeyi düzelten", category: CATEGORIES.OBJECTS },
  { word: "Çanta", hint: "Eşya taşımak için", category: CATEGORIES.OBJECTS },
  { word: "Anahtar", hint: "Kilit açan", category: CATEGORIES.OBJECTS },
  { word: "Kalem", hint: "Yazı yazmak için", category: CATEGORIES.OBJECTS },
  { word: "Kitap", hint: "Okuma materyali", category: CATEGORIES.OBJECTS },
  { word: "Lamba", hint: "Işık veren", category: CATEGORIES.OBJECTS },
  { word: "Ayna", hint: "Yansıma gösteren", category: CATEGORIES.OBJECTS },
  { word: "Masa", hint: "Üzerinde çalışılan mobilya", category: CATEGORIES.OBJECTS },
  { word: "Sandalye", hint: "Oturulan mobilya", category: CATEGORIES.OBJECTS },
  { word: "Yatak", hint: "Uyumak için", category: CATEGORIES.OBJECTS },
  { word: "Dolap", hint: "Eşya saklanan", category: CATEGORIES.OBJECTS },
  { word: "Halter", hint: "Eşya asılan", category: CATEGORIES.OBJECTS },
  { word: "Pencere", hint: "Işık giren", category: CATEGORIES.OBJECTS },
  { word: "Kapı", hint: "Giriş çıkış", category: CATEGORIES.OBJECTS },
  { word: "Halı", hint: "Zemin örtüsü", category: CATEGORIES.OBJECTS },
  { word: "Perde", hint: "Pencere örtüsü", category: CATEGORIES.OBJECTS },
  { word: "Yastık", hint: "Baş konan", category: CATEGORIES.OBJECTS },
  { word: "Yorgan", hint: "Üzerine örtülen", category: CATEGORIES.OBJECTS },
  { word: "Çarşaf", hint: "Yatak örtüsü", category: CATEGORIES.OBJECTS },
  { word: "Havlu", hint: "Kurulama için", category: CATEGORIES.OBJECTS },
  { word: "Sabun", hint: "Temizlik için", category: CATEGORIES.OBJECTS },
  { word: "Şampuan", hint: "Saç yıkama", category: CATEGORIES.OBJECTS },
  { word: "Diş Macunu", hint: "Diş temizliği", category: CATEGORIES.OBJECTS },
  { word: "Tarak", hint: "Saç tarayan", category: CATEGORIES.OBJECTS },
  { word: "Fırça", hint: "Boyama aleti", category: CATEGORIES.OBJECTS },
  { word: "Makas", hint: "Kesme aleti", category: CATEGORIES.OBJECTS },

  // === SPOR ===
  { word: "Futbol", hint: "Topla oynanan spor", category: CATEGORIES.SPORTS },
  { word: "Basketbol", hint: "Potaya top atma sporu", category: CATEGORIES.SPORTS },
  { word: "Voleybol", hint: "File üzerinden top atma", category: CATEGORIES.SPORTS },
  { word: "Tenis", hint: "Raketle oynanan", category: CATEGORIES.SPORTS },
  { word: "Yüzme", hint: "Suda yapılan spor", category: CATEGORIES.SPORTS },
  { word: "Koşu", hint: "Ayakla yapılan spor", category: CATEGORIES.SPORTS },
  { word: "Binicilik", hint: "At ile yapılan spor", category: CATEGORIES.SPORTS },
  { word: "Boks", hint: "Yumrukla yapılan spor", category: CATEGORIES.SPORTS },
  { word: "Golf", hint: "Deliğe top sokma sporu", category: CATEGORIES.SPORTS },
  { word: "Kriket", hint: "Sopa ve top sporu", category: CATEGORIES.SPORTS },
  { word: "Ragbi", hint: "Oval top sporu", category: CATEGORIES.SPORTS },
  { word: "Hentbol", hint: "El ile oynanan", category: CATEGORIES.SPORTS },
  { word: "Okçuluk", hint: "Yayla spor", category: CATEGORIES.SPORTS },
  { word: "Buz Pateni", hint: "Buzda kayma", category: CATEGORIES.SPORTS },
  { word: "Kayak", hint: "Kar sporu", category: CATEGORIES.SPORTS },
  { word: "Snowboard", hint: "Tek tahta ile kar", category: CATEGORIES.SPORTS },
  { word: "Yelken", hint: "Rüzgarla spor", category: CATEGORIES.SPORTS },
  { word: "Sörf", hint: "Dalga sporu", category: CATEGORIES.SPORTS },
  { word: "Atletizm", hint: "Koaşma sporu", category: CATEGORIES.SPORTS },
  { word: "Güreş", hint: "Klasik Türk sporu", category: CATEGORIES.SPORTS },

  // === FİLM/DİZİ ===
  { word: "Titanic", hint: "Gemisi batan film", category: CATEGORIES.MOVIES },
  { word: "Avatar", hint: "Uzaylı filmi", category: CATEGORIES.MOVIES },
  { word: "Star Wars", hint: "Jedi'ler filmi", category: CATEGORIES.MOVIES },
  { word: "Harry Potter", hint: "Büyücü filmi", category: CATEGORIES.MOVIES },
  { word: "Matrix", hint: "Sanal gerçeklik filmi", category: CATEGORIES.MOVIES },
  { word: "James Bond", hint: "Casus filmi", category: CATEGORIES.MOVIES },
  { word: "Marvel", hint: "Süper kahramanlar", category: CATEGORIES.MOVIES },
  { word: "Kurtlar Vadisi", hint: "Türk dizisi", category: CATEGORIES.MOVIES },
  { word: "Ezel", hint: "Ramiz Dayı dizisi", category: CATEGORIES.MOVIES },
  { word: "Arka Sokaklar", hint: "Polis dizisi", category: CATEGORIES.MOVIES },
  { word: "Yaprak Dökümü", hint: "Klasik Türk dizisi", category: CATEGORIES.MOVIES },
  { word: "Gönül", hint: "Küçük Ağa dizisi", category: CATEGORIES.MOVIES },
  { word: "Aşk-ı Memnu", hint: "Bihter dizisi", category: CATEGORIES.MOVIES },
  { word: "Diriliş", hint: "Ertuğrul dizisi", category: CATEGORIES.MOVIES },
  { word: "Muhteşem Yüzyıl", hint: "Kanuni dizisi", category: CATEGORIES.MOVIES },
  { word: "Şahmar", hint: "Yeşilçam filmi", category: CATEGORIES.MOVIES },
  { word: "Hababam Sınıfı", hint: "Komedi filmi", category: CATEGORIES.MOVIES },
  { word: "Recep İvedik", hint: "Komedi filmi", category: CATEGORIES.MOVIES },
  { word: "Vizontele", hint: "Şener Şen filmi", category: CATEGORIES.MOVIES },
  { word: "Gora", hint: "Cem Yılmaz filmi", category: CATEGORIES.MOVIES },

  // === MEYVELER ===
  { word: "Elma", hint: "Kırmızı meyve", category: CATEGORIES.FRUITS },
  { word: "Portakal", hint: "Turuncu meyve", category: CATEGORIES.FRUITS },
  { word: "Muz", hint: "Sarı uzun meyve", category: CATEGORIES.FRUITS },
  { word: "Üzüm", hint: "Salkım meyve", category: CATEGORIES.FRUITS },
  { word: "Karpuz", hint: "Büyük yeşil meyve", category: CATEGORIES.FRUITS },
  { word: "Kavun", hint: "Sarı içli meyve", category: CATEGORIES.FRUITS },
  { word: "Çilek", hint: "Küçük kırmızı meyve", category: CATEGORIES.FRUITS },
  { word: "Kiraz", hint: "Siyah küçük meyve", category: CATEGORIES.FRUITS },
  { word: "Şeftali", hint: "Tüylü meyve", category: CATEGORIES.FRUITS },
  { word: "Armut", hint: "Armut şeklinde meyve", category: CATEGORIES.FRUITS },
  { word: "Nar", hint: "Taneli meyve", category: CATEGORIES.FRUITS },
  { word: "İncir", hint: "Tatlı meyve", category: CATEGORIES.FRUITS },
  { word: "Zeytin", hint: "Siyah küçük meyve", category: CATEGORIES.FRUITS },
  { word: "Limon", hint: "Ekşimsi meyve", category: CATEGORIES.FRUITS },
  { word: "Mandalina", hint: "Kolay soyulan", category: CATEGORIES.FRUITS },
  { word: "Greyfurt", hint: "Büyük turuncu", category: CATEGORIES.FRUITS },
  { word: "Ananas", hint: "Tropikal meyve", category: CATEGORIES.FRUITS },
  { word: "Mango", hint: "Sarı tropikal", category: CATEGORIES.FRUITS },
  { word: "Avokado", hint: "Yağlı meyve", category: CATEGORIES.FRUITS },
  { word: "Kivi", hint: "Tüylü yeşil", category: CATEGORIES.FRUITS },
  { word: "Dut", hint: "Salkım meyve", category: CATEGORIES.FRUITS },
  { word: "Erik", hint: "Mor meyve", category: CATEGORIES.FRUITS },
  { word: "Vişne", hint: "Ekşi kiraz", category: CATEGORIES.FRUITS },
  { word: "Ayva", hint: "Sarı sert meyve", category: CATEGORIES.FRUITS },

  // === İÇECEKLER ===
  { word: "Su", hint: "Hayatın kaynağı", category: CATEGORIES.DRINKS },
  { word: "Kahve", hint: "Uyarıcı içecek", category: CATEGORIES.DRINKS },
  { word: "Çay", hint: "Türklerin favorisi", category: CATEGORIES.DRINKS },
  { word: "Kola", hint: "Gazlı içecek", category: CATEGORIES.DRINKS },
  { word: "Limonata", hint: "Ekşimsi içecek", category: CATEGORIES.DRINKS },
  { word: "Süt", hint: "Beyaz içecek", category: CATEGORIES.DRINKS },
  { word: "Bira", hint: "Alkollü içecek", category: CATEGORIES.DRINKS },
  { word: "Şarap", hint: "Üzümlü alkollü", category: CATEGORIES.DRINKS },
  { word: "Votka", hint: "Berrak içki", category: CATEGORIES.DRINKS },
  { word: "Viski", hint: "Kahverengi içki", category: CATEGORIES.DRINKS },
  { word: "Rakı", hint: "Anadolu içkisi", category: CATEGORIES.DRINKS },
  { word: "Ayran", hint: "Yoğurtlu içecek", category: CATEGORIES.DRINKS },
  { word: "Soda", hint: "Gazlı su", category: CATEGORIES.DRINKS },
  { word: "Meyve Suyu", hint: "Sıkılmış", category: CATEGORIES.DRINKS },
  { word: "Bitki Çayı", hint: "Yeşil çay", category: CATEGORIES.DRINKS },
  { word: "Maté", hint: "Güney Amerika çayı", category: CATEGORIES.DRINKS },
  { word: "Matcha", hint: "Japon çayı", category: CATEGORIES.DRINKS },
  { word: "Cappuccino", hint: "Köpüklü kahve", category: CATEGORIES.DRINKS },
  { word: "Latte", hint: "Sütlü kahve", category: CATEGORIES.DRINKS },
  { word: "Espresso", hint: "Yoğun kahve", category: CATEGORIES.DRINKS },
  { word: "Mocha", hint: "Çikolatalı kahve", category: CATEGORIES.DRINKS },

  // === KIYAFETLER ===
  { word: "Tişört", hint: "Kısa kollu üst", category: CATEGORIES.CLOTHES },
  { word: "Pantolon", hint: "Bacak giyimi", category: CATEGORIES.CLOTHES },
  { word: "Gömlek", hint: "Yakalı üst", category: CATEGORIES.CLOTHES },
  { word: "Elbise", hint: "Tek parça kadın giyimi", category: CATEGORIES.CLOTHES },
  { word: "Etek", hint: "Kadın bacak giyimi", category: CATEGORIES.CLOTHES },
  { word: "Kazak", hint: "Örme üst", category: CATEGORIES.CLOTHES },
  { word: "Ceket", hint: "Üst giyim", category: CATEGORIES.CLOTHES },
  { word: "Mont", hint: "Kışlık üst", category: CATEGORIES.CLOTHES },
  { word: "Şapka", hint: "Baş giyimi", category: CATEGORIES.CLOTHES },
  { word: "Ayakkabı", hint: "Ayak giyimi", category: CATEGORIES.CLOTHES },
  { word: "Çorap", hint: "Ayak giyimi", category: CATEGORIES.CLOTHES },
  { word: "Atkı", hint: "Boynuna takılan", category: CATEGORIES.CLOTHES },
  { word: "Eldiven", hint: "El giyimi", category: CATEGORIES.CLOTHES },
  { word: "Kemer", hint: "Bel kemeri", category: CATEGORIES.CLOTHES },
  { word: "Kravat", hint: "Erkek boyun aksesuarı", category: CATEGORIES.CLOTHES },
  { word: "Papyon", hint: "Resmi aksesuar", category: CATEGORIES.CLOTHES },
  { word: "Kol Düğmesi", hint: "Manşet aksesuarı", category: CATEGORIES.CLOTHES },
  { word: "Külot", hint: "İç çamaşır", category: CATEGORIES.CLOTHES },
  { word: "Sütyen", hint: "Kadın iç giyim", category: CATEGORIES.CLOTHES },
  { word: "Boxer", hint: "Erkek iç giyim", category: CATEGORIES.CLOTHES },
  { word: "Pijama", hint: "Uyku giyimi", category: CATEGORIES.CLOTHES },
  { word: "Sabahlık", hint: "Ev giyimi", category: CATEGORIES.CLOTHES },
  { word: "Büstiyer", hint: "Üst iç giyim", category: CATEGORIES.CLOTHES },
  { word: "Tayt", hint: "Spor giyim", category: CATEGORIES.CLOTHES },
  { word: "Şort", hint: "Kısa pantolon", category: CATEGORIES.CLOTHES },
  { word: "Etek", hint: "Kısa paça", category: CATEGORIES.CLOTHES },

  // === ULAŞIM ===
  { word: "Araba", hint: "Karayolu aracı", category: CATEGORIES.TRANSPORT },
  { word: "Otobüs", hint: "Toplu taşıma", category: CATEGORIES.TRANSPORT },
  { word: "Tren", hint: "Raylı ulaşım", category: CATEGORIES.TRANSPORT },
  { word: "Uçak", hint: "Hava aracı", category: CATEGORIES.TRANSPORT },
  { word: "Gemi", hint: "Deniz aracı", category: CATEGORIES.TRANSPORT },
  { word: "Motorsiklet", hint: "İki tekerlekli araç", category: CATEGORIES.TRANSPORT },
  { word: "Bisiklet", hint: "Pedallı araç", category: CATEGORIES.TRANSPORT },
  { word: "Taksi", hint: "Kiralık araba", category: CATEGORIES.TRANSPORT },
  { word: "Helikopter", hint: "Dönen kanatlı", category: CATEGORIES.TRANSPORT },
  { word: "Metropoll", hint: "Metro", category: CATEGORIES.TRANSPORT },
  { word: "Tramvay", hint: "Raylı toplu taşıma", category: CATEGORIES.TRANSPORT },
  { word: "Tren", hint: "Şehirler arası", category: CATEGORIES.TRANSPORT },
  { word: "Gemi", hint: "Yolcu gemisi", category: CATEGORIES.TRANSPORT },
  { word: "Vapur", hint: "Deniz otobüsü", category: CATEGORIES.TRANSPORT },
  { word: "Tekne", hint: "Küçük deniz aracı", category: CATEGORIES.TRANSPORT },
  { word: "Yat", hint: "Lüks deniz aracı", category: CATEGORIES.TRANSPORT },
  { word: "Scooter", hint: "Küçük motorsiklet", category: CATEGORIES.TRANSPORT },
  { word: "Kaykay", hint: "Tekerlekli tahta", category: CATEGORIES.TRANSPORT },
  { word: "Kayak", hint: "Kış taşıtı", category: CATEGORIES.TRANSPORT },
  { word: "Sörf tahtası", hint: "Deniz tahtası", category: CATEGORIES.TRANSPORT },
  { word: "Roket", hint: "Uzay aracı", category: CATEGORIES.TRANSPORT },

  // === DOĞA ===
  { word: "Dağ", hint: "Yüksek kara", category: CATEGORIES.NATURE },
  { word: "Deniz", hint: "Tuzlu su", category: CATEGORIES.NATURE },
  { word: "Göl", hint: "Tatlı su birikintisi", category: CATEGORIES.NATURE },
  { word: "Nehir", hint: "Akan su", category: CATEGORIES.NATURE },
  { word: "Orman", hint: "Ağaçlık alan", category: CATEGORIES.NATURE },
  { word: "Çöl", hint: "Kumlu alan", category: CATEGORIES.NATURE },
  { word: "Çiçek", hint: "Bitki", category: CATEGORIES.NATURE },
  { word: "Ağaç", hint: "Odunsu bitki", category: CATEGORIES.NATURE },
  { word: "Taş", hint: "Sert madde", category: CATEGORIES.NATURE },
  { word: "Bulut", hint: "Gökyüzü", category: CATEGORIES.NATURE },
  { word: "Güneş", hint: "Isı kaynağı", category: CATEGORIES.NATURE },
  { word: "Ay", hint: "Gece ışığı", category: CATEGORIES.NATURE },
  { word: "Yıldız", hint: "Gökyüzü noktası", category: CATEGORIES.NATURE },
  { word: "Kuyu", hint: "Yeraltı suyu", category: CATEGORIES.NATURE },
  { word: "Şelale", hint: "Düşen su", category: CATEGORIES.NATURE },
  { word: "Volkan", hint: "Püsküren dağ", category: CATEGORIES.NATURE },
  { word: "Deprem", hint: "Yer sarsımı", category: CATEGORIES.NATURE },
  { word: "Fırtına", hint: "Şiddetli hava", category: CATEGORIES.NATURE },
  { word: "Kar", hint: "Beyaz yağış", category: CATEGORIES.NATURE },
  { word: "Dolu", hint: "Buz tanesi", category: CATEGORIES.NATURE },
  { word: "Sis", hint: "Görüş azlığı", category: CATEGORIES.NATURE },
  { word: "Rüzgar", hint: "Hareketli hava", category: CATEGORIES.NATURE },
  { word: "Gökkuşağı", hint: "Renkli kavis", category: CATEGORIES.NATURE },
  { word: "Şimşek", hint: "Elektrik ışık", category: CATEGORIES.NATURE },
  { word: "Toz", hint: "Havada asılı", category: CATEGORIES.NATURE },

  // === TEKNOLOJİ ===
  { word: "Laptop", hint: "Taşınabilir bilgisayar", category: CATEGORIES.TECH },
  { word: "Tablet", hint: "Elektronik defter", category: CATEGORIES.TECH },
  { word: "Kamera", hint: "Fotoğraf çeken", category: CATEGORIES.TECH },
  { word: "Kulaklık", hint: "Ses dinleme", category: CATEGORIES.TECH },
  { word: "Konsol", hint: "Oyun makinesi", category: CATEGORIES.TECH },
  { word: "Drone", hint: "Uzaktan kumandalı uçak", category: CATEGORIES.TECH },
  { word: "Robot", hint: "Otomatik makine", category: CATEGORIES.TECH },
  { word: "Akıllı Saat", hint: "Bilezik teknoloji", category: CATEGORIES.TECH },
  { word: "Yazıcı", hint: "Kağıda basan", category: CATEGORIES.TECH },
  { word: "Projeksiyon", hint: "Görüntü yansıtan", category: CATEGORIES.TECH },
  { word: "Tarayıcı", hint: "Belge tarama", category: CATEGORIES.TECH },
  { word: "Faks", hint: "Belge gönderme", category: CATEGORIES.TECH },
  { word: "Xerox", hint: "Kopyalama", category: CATEGORIES.TECH },
  { word: "Modem", hint: "İnternet bağlantısı", category: CATEGORIES.TECH },
  { word: "Router", hint: "Ağ dağıtıcı", category: CATEGORIES.TECH },
  { word: "Harddisk", hint: "Depolama birimi", category: CATEGORIES.TECH },
  { word: "SSD", hint: "Hızlı depolama", category: CATEGORIES.TECH },
  { word: "RAM", hint: "Hafıza birimi", category: CATEGORIES.TECH },
  { word: "İşlemci", hint: "Beyin", category: CATEGORIES.TECH },
  { word: "Ekran Kartı", hint: "Görüntü birimi", category: CATEGORIES.TECH },
  { word: "Ses Kartı", hint: "Ses birimi", category: CATEGORIES.TECH },
  { word: "Power Bank", hint: "Taşınabilir pil", category: CATEGORIES.TECH },
  { word: "Şarj Aleti", hint: "Pil dolduran", category: CATEGORIES.TECH },

  // === MÜZİK ===
  { word: "Gitar", hint: "Telli çalgı", category: CATEGORIES.MUSIC },
  { word: "Piyano", hint: "Tuşlu çalgı", category: CATEGORIES.MUSIC },
  { word: "Davul", hint: "Vurmalı çalgı", category: CATEGORIES.MUSIC },
  { word: "Keman", hint: "Yaylı çalgı", category: CATEGORIES.MUSIC },
  { word: "Ney", hint: "Türk müzik aleti", category: CATEGORIES.MUSIC },
  { word: "Bağlama", hint: "Türk halk çalgısı", category: CATEGORIES.MUSIC },
  { word: "Saksafon", hint: "Üflemeli çalgı", category: CATEGORIES.MUSIC },
  { word: "Mikrofon", hint: "Ses alan", category: CATEGORIES.MUSIC },
  { word: "Hoparlör", hint: "Ses çıkaran", category: CATEGORIES.MUSIC },
  { word: "Amfi", hint: "Ses yükselten", category: CATEGORIES.MUSIC },
  { word: "Flüt", hint: "Üflemeli çalgı", category: CATEGORIES.MUSIC },
  { word: "Klarnet", hint: "Nefesli çalgı", category: CATEGORIES.MUSIC },
  { word: "Bas Gitar", hint: "Derin telli", category: CATEGORIES.MUSIC },
  { word: "Elektro Gitar", hint: "Elektrikli telli", category: CATEGORIES.MUSIC },
  { word: "Bateri", hint: "Vurmalı", category: CATEGORIES.MUSIC },
  { word: "Keman", hint: "Yaylı", category: CATEGORIES.MUSIC },
  { word: "Çalgı", hint: "Türk telli", category: CATEGORIES.MUSIC },
  { word: "Ud", hint: "Orta doğu telli", category: CATEGORIES.MUSIC },
  { word: "Kanun", hint: "Türk telli", category: CATEGORIES.MUSIC },
  { word: "Darbuka", hint: "Vurmalı Türk", category: CATEGORIES.MUSIC },
  { word: "Bendir", hint: "Göğüslü davul", category: CATEGORIES.MUSIC },

  // === VÜCUT ===
  { word: "Göz", hint: "Görme organı", category: CATEGORIES.BODY },
  { word: "Kulak", hint: "Duyma organı", category: CATEGORIES.BODY },
  { word: "Burun", hint: "Koklama organı", category: CATEGORIES.BODY },
  { word: "Ağız", hint: "Konuşma organı", category: CATEGORIES.BODY },
  { word: "El", hint: "Tutma organı", category: CATEGORIES.BODY },
  { word: "Ayak", hint: "Yürüme organı", category: CATEGORIES.BODY },
  { word: "Beyin", hint: "Düşünme organı", category: CATEGORIES.BODY },
  { word: "Kalp", hint: "Atan organ", category: CATEGORIES.BODY },
  { word: "Dil", hint: "Tat alma", category: CATEGORIES.BODY },
  { word: "Diş", hint: "Çiğneme", category: CATEGORIES.BODY },
  { word: "Saç", hint: "Baş örtüsü", category: CATEGORIES.BODY },
  { word: "Tırnak", hint: "Sert uzantı", category: CATEGORIES.BODY },
  { word: "Cilt", hint: "Vücut örtüsü", category: CATEGORIES.BODY },
  { word: "Kemik", hint: "İskelet", category: CATEGORIES.BODY },
  { word: "Kas", hint: "Hareket sağlar", category: CATEGORIES.BODY },
  { word: "Karaciğer", hint: "Süzme organı", category: CATEGORIES.BODY },
  { word: "Böbrek", hint: "Süzme", category: CATEGORIES.BODY },
  { word: "Mide", hint: "Sindirim organı", category: CATEGORIES.BODY },
  { word: "Bağırsak", hint: "Sindirim", category: CATEGORIES.BODY },
  { word: "Akciğer", hint: "Nefes alma", category: CATEGORIES.BODY },
  { word: "Kalp", hint: "Kan pompalama", category: CATEGORIES.BODY },
  { word: "Damar", hint: "Kan taşıyıcı", category: CATEGORIES.BODY },
  { word: "Sinir", hint: "Sinyal taşıyıcı", category: CATEGORIES.BODY },

  // === RENKLER ===
  { word: "Kırmızı", hint: "Kan rengi", category: CATEGORIES.COLORS },
  { word: "Mavi", hint: "Gökyüzü rengi", category: CATEGORIES.COLORS },
  { word: "Sarı", hint: "Güneş rengi", category: CATEGORIES.COLORS },
  { word: "Yeşil", hint: "Yaprak rengi", category: CATEGORIES.COLORS },
  { word: "Turuncu", hint: "Portakal rengi", category: CATEGORIES.COLORS },
  { word: "Mor", hint: "Üzüm rengi", category: CATEGORIES.COLORS },
  { word: "Pembe", hint: "Gül rengi", category: CATEGORIES.COLORS },
  { word: "Kahverengi", hint: "Toprak rengi", category: CATEGORIES.COLORS },
  { word: "Siyah", hint: "Karanlık", category: CATEGORIES.COLORS },
  { word: "Beyaz", hint: "Kar rengi", category: CATEGORIES.COLORS },
  { word: "Gri", hint: "Bulut rengi", category: CATEGORIES.COLORS },
  { word: "Lacivert", hint: "Koyu mavi", category: CATEGORIES.COLORS },
  { word: "Turkuaz", hint: "Deniz mavisi", category: CATEGORIES.COLORS },
  { word: "Bordo", hint: "Koyu kırmızı", category: CATEGORIES.COLORS },
  { word: "Bej", hint: "Açık kahve", category: CATEGORIES.COLORS },
  { word: "Krem", hint: "Açık sarı", category: CATEGORIES.COLORS },
  { word: "Gümüş", hint: "Parlak gri", category: CATEGORIES.COLORS },
  { word: "Altın", hint: "Sarı parlak", category: CATEGORIES.COLORS },
  { word: "Bronz", hint: "Kahve sarı", category: CATEGORIES.COLORS },

  // === SAYILAR ===
  { word: "Bir", hint: "İlk sayı", category: CATEGORIES.NUMBERS },
  { word: "İki", hint: "Çift", category: CATEGORIES.NUMBERS },
  { word: "Üç", hint: "Üçlü", category: CATEGORIES.NUMBERS },
  { word: "Dört", hint: "Dörtlü", category: CATEGORIES.NUMBERS },
  { word: "Beş", hint: "El sayısı", category: CATEGORIES.NUMBERS },
  { word: "On", hint: "İki el", category: CATEGORIES.NUMBERS },
  { word: "Yirmi", hint: "İki on", category: CATEGORIES.NUMBERS },
  { word: "Yüz", hint: "On on", category: CATEGORIES.NUMBERS },
  { word: "Bin", hint: "On yüz", category: CATEGORIES.NUMBERS },
  { word: "Milyon", hint: "Büyük sayı", category: CATEGORIES.NUMBERS },
  { word: "Sıfır", hint: "Başlangıç", category: CATEGORIES.NUMBERS },
  { word: "Yarım", hint: "0.5", category: CATEGORIES.NUMBERS },
  { word: "Çeyrek", hint: "0.25", category: CATEGORIES.NUMBERS },
  { word: "Ondalık", hint: "Virgüllü sayı", category: CATEGORIES.NUMBERS },
  { word: "Negatif", hint: "Eksi sayı", category: CATEGORIES.NUMBERS },
  { word: "Pozitif", hint: "Artı sayı", category: CATEGORIES.NUMBERS },
  { word: "Asal", hint: "Bölünemez", category: CATEGORIES.NUMBERS },
  { word: "Ondalıklı", hint: "Kesirli sayı", category: CATEGORIES.NUMBERS },
  { word: "Tam Sayı", hint: "Kesirsiz", category: CATEGORIES.NUMBERS },
  { word: "Rakam", hint: "Sayı işareti", category: CATEGORIES.NUMBERS },
  { word: "Basamak", hint: "Sayı yeri", category: CATEGORIES.NUMBERS },

  // === AYLAR ===
  { word: "Ocak", hint: "İlk ay", category: CATEGORIES.MONTHS },
  { word: "Şubat", hint: "Kısa ay", category: CATEGORIES.MONTHS },
  { word: "Mart", hint: "Bahar başlangıcı", category: CATEGORIES.MONTHS },
  { word: "Nisan", hint: "Yaşmur ayı", category: CATEGORIES.MONTHS },
  { word: "Mayıs", hint: "Anneler ayı", category: CATEGORIES.MONTHS },
  { word: "Haziran", hint: "Yaz ayı", category: CATEGORIES.MONTHS },
  { word: "Temmuz", hint: "Sıcak ay", category: CATEGORIES.MONTHS },
  { word: "Ağustos", hint: "Kurban bayramı", category: CATEGORIES.MONTHS },
  { word: "Eylül", hint: "Öğretmenler ayı", category: CATEGORIES.MONTHS },
  { word: "Ekim", hint: "Kurtuluş ayı", category: CATEGORIES.MONTHS },
  { word: "Kasım", hint: "Atatürk'ü anma", category: CATEGORIES.MONTHS },
  { word: "Aralık", hint: "Son ay", category: CATEGORIES.MONTHS },

  // === MEVSİMLER ===
  { word: "İlkbahar", hint: "Çiçek açma", category: CATEGORIES.SEASONS },
  { word: "Yaz", hint: "Sıcak sezon", category: CATEGORIES.SEASONS },
  { word: "Sonbahar", hint: "Yaprak dökümü", category: CATEGORIES.SEASONS },
  { word: "Kış", hint: "Kar sezonu", category: CATEGORIES.SEASONS },
  { word: "Mevsim", hint: "Dört dönem", category: CATEGORIES.SEASONS },
  { word: "Don", hint: "Buzlama", category: CATEGORIES.SEASONS },
  { word: "Erime", hint: "Kar gitmesi", category: CATEGORIES.SEASONS },
  { word: "Çiçeklenme", hint: "Bahar", category: CATEGORIES.SEASONS },
  { word: "Hasat", hint: "Toplama", category: CATEGORIES.SEASONS },
  { word: "Kuraklık", hint: "Susuzluk", category: CATEGORIES.SEASONS },

  // === ÜLKELER ===
  { word: "Türkiye", hint: "Anadolu", category: CATEGORIES.COUNTRIES },
  { word: "Almanya", hint: "Avrupa'nın kalbi", category: CATEGORIES.COUNTRIES },
  { word: "Fransa", hint: "Paris'in ülkesi", category: CATEGORIES.COUNTRIES },
  { word: "İngiltere", hint: "Londra'nın ülkesi", category: CATEGORIES.COUNTRIES },
  { word: "İtalya", hint: "Roma'nın ülkesi", category: CATEGORIES.COUNTRIES },
  { word: "İspanya", hint: "Flamenko", category: CATEGORIES.COUNTRIES },
  { word: "Portekiz", hint: "Lizbon", category: CATEGORIES.COUNTRIES },
  { word: "Yunanistan", hint: "Antik ülke", category: CATEGORIES.COUNTRIES },
  { word: "Rusya", hint: "En büyük ülke", category: CATEGORIES.COUNTRIES },
  { word: "Çin", hint: "Kalabalık ülke", category: CATEGORIES.COUNTRIES },
  { word: "Japonya", hint: "Ada ülkesi", category: CATEGORIES.COUNTRIES },
  { word: "Hindistan", hint: "Farsçe", category: CATEGORIES.COUNTRIES },
  { word: "ABD", hint: "Amerika", category: CATEGORIES.COUNTRIES },
  { word: "Kanada", hint: "Kuzey Amerika", category: CATEGORIES.COUNTRIES },
  { word: "Meksika", hint: "Taco", category: CATEGORIES.COUNTRIES },
  { word: "Brezilya", hint: "Futbol", category: CATEGORIES.COUNTRIES },
  { word: "Arjantin", hint: "Tango", category: CATEGORIES.COUNTRIES },
  { word: "Mısır", hint: "Piramitler", category: CATEGORIES.COUNTRIES },
  { word: "Güney Afrika", hint: " safari", category: CATEGORIES.COUNTRIES },
  { word: "Avustralya", hint: "Kanguru", category: CATEGORIES.COUNTRIES },
  { word: "Yeni Zelanda", hint: "Koyun", category: CATEGORIES.COUNTRIES },
  { word: "İsveç", hint: "İklim", category: CATEGORIES.COUNTRIES },
  { word: "Norveç", hint: "Körfez", category: CATEGORIES.COUNTRIES },
  { word: "Danimarka", hint: "Vikingler", category: CATEGORIES.COUNTRIES },
  { word: "Hollanda", hint: "Laleler", category: CATEGORIES.COUNTRIES },
  { word: "İsviçre", hint: "Çikolata", category: CATEGORIES.COUNTRIES },
  { word: "Belçika", hint: "Waffle", category: CATEGORIES.COUNTRIES },
  { word: "Avusturya", hint: "Mozart", category: CATEGORIES.COUNTRIES },
  { word: "Polonya", hint: "Vodka", category: CATEGORIES.COUNTRIES },
  { word: "Çekya", hint: "Bira", category: CATEGORIES.COUNTRIES },
  { word: "Macaristan", hint: "Tatlılar", category: CATEGORIES.COUNTRIES },
  { word: "Romanya", hint: "Drakula", category: CATEGORIES.COUNTRIES },
  { word: "Bulgaristan", hint: "Gül", category: CATEGORIES.COUNTRIES },

  // === BİLİM ===
  { word: "Fizik", hint: "Enerji bilimi", category: CATEGORIES.SCIENCE },
  { word: "Kimya", hint: "Madde bilimi", category: CATEGORIES.SCIENCE },
  { word: "Biyoloji", hint: "Canlı bilimi", category: CATEGORIES.SCIENCE },
  { word: "Astronomi", hint: "Uzay bilimi", category: CATEGORIES.SCIENCE },
  { word: "Jeoloji", hint: "Yer bilimi", category: CATEGORIES.SCIENCE },
  { word: "Ekoloji", hint: "Çevre bilimi", category: CATEGORIES.SCIENCE },
  { word: "Genetik", hint: "DNA bilimi", category: CATEGORIES.SCIENCE },
  { word: "Nörobilim", hint: "Beyin bilimi", category: CATEGORIES.SCIENCE },
  { word: "Matematik", hint: "Sayı bilimi", category: CATEGORIES.SCIENCE },
  { word: "İstatistik", hint: "Veri bilimi", category: CATEGORIES.SCIENCE },
  { word: "Bilgisayar Bilimi", hint: "Yazılım", category: CATEGORIES.SCIENCE },
  { word: "Tıp", hint: "Sağlık bilimi", category: CATEGORIES.SCIENCE },
  { word: "Eczacılık", hint: "İlaç bilimi", category: CATEGORIES.SCIENCE },
  { word: "Mühendislik", hint: "Tasarım bilimi", category: CATEGORIES.SCIENCE },
  { word: "Arkeoloji", hint: "Kazı bilimi", category: CATEGORIES.SCIENCE },
  { word: "Antropoloji", hint: "İnsan bilimi", category: CATEGORIES.SCIENCE },
  { word: "Psikoloji", hint: "Ruhsal bilim", category: CATEGORIES.SCIENCE },
  { word: "Sosyoloji", hint: "Toplum bilimi", category: CATEGORIES.SCIENCE },
  { word: "Ekonomi", hint: "Para bilimi", category: CATEGORIES.SCIENCE },
  { word: "Hukuk", hint: "Yasa bilimi", category: CATEGORIES.SCIENCE },
  { word: "Eğitim", hint: "Öğretim bilimi", category: CATEGORIES.SCIENCE },
  { word: "Felsefe", hint: "Düşünce bilimi", category: CATEGORIES.SCIENCE },

  // === SANAT ===
  { word: "Resim", hint: "Görsel sanat", category: CATEGORIES.ART },
  { word: "Heykel", hint: "Üç boyutlu sanat", category: CATEGORIES.ART },
  { word: "Mimari", hint: "Tasarım sanatı", category: CATEGORIES.ART },
  { word: "Fotoğraf", hint: "Işık sanatı", category: CATEGORIES.ART },
  { word: "Tiyatro", hint: "Sahne sanatı", category: CATEGORIES.ART },
  { word: "Opera", hint: "Şarkı sanatı", category: CATEGORIES.ART },
  { word: "Bale", hint: "Dans sanatı", category: CATEGORIES.ART },
  { word: "Sinema", hint: "Hareket sanatı", category: CATEGORIES.ART },
  { word: "Televizyon", hint: "Yayın sanatı", category: CATEGORIES.ART },
  { word: "Radyo", hint: "Ses sanatı", category: CATEGORIES.ART },
  { word: "Külot", hint: "İç giyim", category: CATEGORIES.ART },
  { word: "Mozaik", hint: "Parça sanatı", category: CATEGORIES.ART },
  { word: "Seramik", hint: "Kil sanatı", category: CATEGORIES.ART },
  { word: "Cam", hint: "Şeffaf sanat", category: CATEGORIES.ART },
  { word: "Metal", hint: "Sert sanat", category: CATEGORIES.ART },
  { word: "Ahşap", hint: "Odun sanatı", category: CATEGORIES.ART },
  { word: "Kağıt", hint: "Yüzey sanatı", category: CATEGORIES.ART },
  { word: "Kumaş", hint: "Tekstil sanatı", category: CATEGORIES.ART },
  { word: "Deri", hint: "Hayvani sanat", category: CATEGORIES.ART },
  { word: "Taş", hint: "Doğal sanat", category: CATEGORIES.ART },
  { word: "Plastik", hint: "Yapay sanat", category: CATEGORIES.ART },

  // === EDEBİYAT ===
  { word: "Roman", hint: "Uzun hikaye", category: CATEGORIES.LITERATURE },
  { word: "Hikaye", hint: "Kısa anlatım", category: CATEGORIES.LITERATURE },
  { word: "Şiir", hint: "Dizili anlatım", category: CATEGORIES.LITERATURE },
  { word: "Deneme", hint: "Görüş yazısı", category: CATEGORIES.LITERATURE },
  { word: "Makale", hint: "Bilgi yazısı", category: CATEGORIES.LITERATURE },
  { word: "Fıkra", hint: "Kısa hikaye", category: CATEGORIES.LITERATURE },
  { word: "Tiyatro", hint: "Sahne eseri", category: CATEGORIES.LITERATURE },
  { word: "Oyun", hint: "Sahne eseri", category: CATEGORIES.LITERATURE },
  { word: "Biyografi", hint: "Yaşam öyküsü", category: CATEGORIES.LITERATURE },
  { word: "Otobiyografi", hint: "Kendi yaşamı", category: CATEGORIES.LITERATURE },
  { word: "Tarih", hint: "Geçmiş", category: CATEGORIES.LITERATURE },
  { word: "Efsane", hint: "Mitolojik hikaye", category: CATEGORIES.LITERATURE },
  { word: "Masal", hint: "Çocuk hikayesi", category: CATEGORIES.LITERATURE },
  { word: "Destan", hint: "Kahramanlık", category: CATEGORIES.LITERATURE },
  { word: "Manzume", hint: "Dizili şiir", category: CATEGORIES.LITERATURE },
  { word: "Lirik", hint: "Duygu şiiri", category: CATEGORIES.LITERATURE },
  { word: "Epik", hint: "Kahraman şiiri", category: CATEGORIES.LITERATURE },
  { word: "Satirik", hint: "Yergi", category: CATEGORIES.LITERATURE },
  { word: "Komedya", hint: "Eğlence", category: CATEGORIES.LITERATURE },
  { word: "Tragedi", hint: "Acı son", category: CATEGORIES.LITERATURE },
  { word: "Dram", hint: "Oyun", category: CATEGORIES.LITERATURE },

  // === TARİH ===
  { word: "Osmanlı", hint: "Türk imparatorluğu", category: CATEGORIES.HISTORY },
  { word: "Roma", hint: "İtalyan imparatorluğu", category: CATEGORIES.HISTORY },
  { word: "Bizans", hint: "Doğu Roma", category: CATEGORIES.HISTORY },
  { word: "Selçuklu", hint: "Türk devleti", category: CATEGORIES.HISTORY },
  { word: "Memlük", hint: "Köle devleti", category: CATEGORIES.HISTORY },
  { word: "Moğol", hint: "Attila devleti", category: CATEGORIES.HISTORY },
  { word: "Sasani", hint: "İran devleti", category: CATEGORIES.HISTORY },
  { word: "Abbasi", hint: "Arap devleti", category: CATEGORIES.HISTORY },
  { word: "Endülüs", hint: "İspanya İslam", category: CATEGORIES.HISTORY },
  { word: "Haçlı Seferi", hint: "Kudüs seferleri", category: CATEGORIES.HISTORY },
  { word: "Rönesans", hint: "Yeniden doğuş", category: CATEGORIES.HISTORY },
  { word: "Reform", hint: "Din değişikliği", category: CATEGORIES.HISTORY },
  { word: "Sanay Devrimi", hint: "Makineleşme", category: CATEGORIES.HISTORY },
  { word: "Fransız Devrimi", hint: "Cumhuriyet", category: CATEGORIES.HISTORY },
  { word: "Kurtuluş Savaşı", hint: "Türk bağımsızlığı", category: CATEGORIES.HISTORY },
  { word: "Cumhuriyet", hint: "Yönetim biçimi", category: CATEGORIES.HISTORY },
  { word: "Saltanat", hint: "Kral yönetimi", category: CATEGORIES.HISTORY },
  { word: "İmparatorluk", hint: "Büyük devlet", category: CATEGORIES.HISTORY },
  { word: "Koloni", hint: "Sömürge", category: CATEGORIES.HISTORY },
  { word: "Bağımsızlık", hint: "Özgürlük", category: CATEGORIES.HISTORY },
  { word: "Demokrasi", hint: "Halk yönetimi", category: CATEGORIES.HISTORY },
  { word: "Cumhuriyet", hint: "Halk devleti", category: CATEGORIES.HISTORY },

  // === OKUL ===
  { word: "Sınıf", hint: "Öğrenci grubu", category: CATEGORIES.SCHOOL },
  { word: "Öğretmen", hint: "Ders veren", category: CATEGORIES.SCHOOL },
  { word: "Müdür", hint: "Okul yöneticisi", category: CATEGORIES.SCHOOL },
  { word: "Müfettiş", hint: "Denetçi", category: CATEGORIES.SCHOOL },
  { word: "Kantin", hint: "Yemekhane", category: CATEGORIES.SCHOOL },
  { word: "Kütüphane", hint: "Kitaplık", category: CATEGORIES.SCHOOL },
  { word: "Laboratuvar", hint: "Deney odası", category: CATEGORIES.SCHOOL },
  { word: "Sınav", hint: "Değerlendirme", category: CATEGORIES.SCHOOL },
  { word: "Diploma", hint: "Mezuniyet", category: CATEGORIES.SCHOOL },
  { word: "Not", hint: "Puan", category: CATEGORIES.SCHOOL },
  { word: "Ödev", hint: "Ev çalışması", category: CATEGORIES.SCHOOL },
  { word: "Proje", hint: "Çalışma", category: CATEGORIES.SCHOOL },
  { word: "Tez", hint: "Akademik çalışma", category: CATEGORIES.SCHOOL },
  { word: "Seminer", hint: "Ders", category: CATEGORIES.SCHOOL },
  { word: "Konferans", hint: "Toplantı", category: CATEGORIES.SCHOOL },
  { word: "Staj", hint: "İş deneyimi", category: CATEGORIES.SCHOOL },
  { word: "Mezun", hint: "Okul bitiren", category: CATEGORIES.SCHOOL },
  { word: "Lisans", hint: "Önlisans", category: CATEGORIES.SCHOOL },
  { word: "Yüksek Lisans", hint: "Master", category: CATEGORIES.SCHOOL },
  { word: "Doktora", hint: "PhD", category: CATEGORIES.SCHOOL },

  // === EV ===
  { word: "Salon", hint: "Oturma odası", category: CATEGORIES.HOME },
  { word: "Mutfak", hint: "Yemek pişirme", category: CATEGORIES.HOME },
  { word: "Yatak Odası", hint: "Uyku odası", category: CATEGORIES.HOME },
  { word: "Banyo", hint: "Yıkanma odası", category: CATEGORIES.HOME },
  { word: "Tuvalet", hint: "Lavabo", category: CATEGORIES.HOME },
  { word: "Teras", hint: "Bahçe alanı", category: CATEGORIES.HOME },
  { word: "Balkon", hint: "Dış mekan", category: CATEGORIES.HOME },
  { word: "Çatı", hint: "Ev üstü", category: CATEGORIES.HOME },
  { word: "Bodrum", hint: "Depolama", category: CATEGORIES.HOME },
  { word: "Garaj", hint: "Araç yeri", category: CATEGORIES.HOME },
  { word: "Bahçe", hint: "Yeşil alan", category: CATEGORIES.HOME },
  { word: "Avlu", hint: "Dış mekan", category: CATEGORIES.HOME },
  { word: "Kapı", hint: "Giriş", category: CATEGORIES.HOME },
  { word: "Pencere", hint: "Işıklık", category: CATEGORIES.HOME },
  { word: "Merdiven", hint: "Kat bağlantısı", category: CATEGORIES.HOME },
  { word: "Asansör", hint: "Yürüyen merdiven", category: CATEGORIES.HOME },
  { word: "Klima", hint: "Sıcaklık ayarı", category: CATEGORIES.HOME },
  { word: "Isıtma", hint: "Sıcaklık", category: CATEGORIES.HOME },
  { word: "Sofra", hint: "Yemek masası", category: CATEGORIES.HOME },
  { word: "Koltuk", hint: "Oturma yeri", category: CATEGORIES.HOME },
  { word: "Halı", hint: "Zemin örtüsü", category: CATEGORIES.HOME },
  { word: "Perde", hint: "Pencere örtüsü", category: CATEGORIES.HOME },

  // === HAVA ===
  { word: "Güneşli", hint: "Parlak", category: CATEGORIES.WEATHER },
  { word: "Bulutlu", hint: "Kapalı", category: CATEGORIES.WEATHER },
  { word: "Yağmurlu", hint: "Islak", category: CATEGORIES.WEATHER },
  { word: "Karlı", hint: "Beyaz", category: CATEGORIES.WEATHER },
  { word: "Rüzgarlı", hint: "Esrarengiz", category: CATEGORIES.WEATHER },
  { word: "Sisli", hint: "Görüş az", category: CATEGORIES.WEATHER },
  { word: "Sıcak", hint: "Yüksek sıcaklık", category: CATEGORIES.WEATHER },
  { word: "Soğuk", hint: "Düşük sıcaklık", category: CATEGORIES.WEATHER },
  { word: "Ilıman", hint: "Orta sıcaklık", category: CATEGORIES.WEATHER },
  { word: "Fırtınalı", hint: "Şiddetli", category: CATEGORIES.WEATHER },
  { word: "Kasırgalı", hint: "Kuvvetli rüzgar", category: CATEGORIES.WEATHER },
  { word: "Dolu fırtınası", hint: "Buz taneli", category: CATEGORIES.WEATHER },
  { word: "Gökkuşağı", hint: "Renkli", category: CATEGORIES.WEATHER },
  { word: "Şimşekli", hint: "Elektrik", category: CATEGORIES.WEATHER },
  { word: "Açık", hint: "Güneşli", category: CATEGORIES.WEATHER },
  { word: "Kapalı", hint: "Bulutlu", category: CATEGORIES.WEATHER },
  { word: "Serin", hint: "Hoş", category: CATEGORIES.WEATHER },
  { word: "Bunaltıcı", hint: "Çok sıcak", category: CATEGORIES.WEATHER },
  { word: "Dondurucu", hint: "Çok soğuk", category: CATEGORIES.WEATHER },
  { word: "Nemli", hint: "Islı", category: CATEGORIES.WEATHER },
  { word: "Kuru", hint: "Susuz", category: CATEGORIES.WEATHER },
  { word: "Rahat", hint: "Hoş hava", category: CATEGORIES.WEATHER },

  // === DUYGULAR ===
  { word: "Mutlu", hint: "Sevinçli", category: CATEGORIES.FEELINGS },
  { word: "Üzgün", hint: "Pişman", category: CATEGORIES.FEELINGS },
  { word: "Korkmuş", hint: "Tehdit altında", category: CATEGORIES.FEELINGS },
  { word: "Öfkeli", hint: "Kızgın", category: CATEGORIES.FEELINGS },
  { word: "Şaşkın", hint: "Hayret", category: CATEGORIES.FEELINGS },
  { word: "Ümitli", hint: "Umutsuz", category: CATEGORIES.FEELINGS },
  { word: "Hayal kırıklığı", hint: "Üzülmüş", category: CATEGORIES.FEELINGS },
  { word: "Sevinçli", hint: "Mutlu", category: CATEGORIES.FEELINGS },
  { word: "Huzurlu", hint: "Rahat", category: CATEGORIES.FEELINGS },
  { word: "Endişeli", hint: "Korku", category: CATEGORIES.FEELINGS },
  { word: "Meraklı", hint: "İlgili", category: CATEGORIES.FEELINGS },
  { word: "Sıkılmış", hint: "Bunalım", category: CATEGORIES.FEELINGS },
  { word: "Yorgun", hint: "Uykulu", category: CATEGORIES.FEELINGS },
  { word: "Enerjik", hint: "Dinamik", category: CATEGORIES.FEELINGS },
  { word: "Tembel", hint: "Ateşsiz", category: CATEGORIES.FEELINGS },
  { word: "Cesur", hint: "Korkusuz", category: CATEGORIES.FEELINGS },
  { word: "Korkak", hint: "Çeking", category: CATEGORIES.FEELINGS },
  { word: "Cimri", hint: "Açgözlü", category: CATEGORIES.FEELINGS },
  { word: "Cömert", hint: "El açık", category: CATEGORIES.FEELINGS },
  { word: "Benciller", hint: "Bencil", category: CATEGORIES.FEELINGS },
  { word: "Sabırlı", hint: "Tükenmez", category: CATEGORIES.FEELINGS },
  { word: "Tatmin olmuş", hint: "Yeterli", category: CATEGORIES.FEELINGS },
  { word: "Memnun", hint: "Şükran", category: CATEGORIES.FEELINGS },
  { word: "Kıskanç", hint: "İlgne", category: CATEGORIES.FEELINGS },
  { word: "İlgisiz", hint: "Kayıtsız", category: CATEGORIES.FEELINGS },

  // === EYLEMLER ===
  { word: "Koşmak", hint: "Hızlı yürüme", category: CATEGORIES.ACTIONS },
  { word: "Yürümek", hint: "Adım atma", category: CATEGORIES.ACTIONS },
  { word: "Zıplamak", hint: "Yukarı sıçrama", category: CATEGORIES.ACTIONS },
  { word: "Atlamak", hint: "Yukarı çıkma", category: CATEGORIES.ACTIONS },
  { word: "Düşmek", hint: "Aşağı inme", category: CATEGORIES.ACTIONS },
  { word: "Uçmak", hint: "Havada gitme", category: CATEGORIES.ACTIONS },
  { word: "Yüzmek", hint: "Suda gitme", category: CATEGORIES.ACTIONS },
  { word: "Dalmak", hint: "Derine inme", category: CATEGORIES.ACTIONS },
  { word: "Oturmak", hint: "Oturma pozisyonu", category: CATEGORIES.ACTIONS },
  { word: "Kalkmak", hint: "Ayağa kalkma", category: CATEGORIES.ACTIONS },
  { word: "Yatmak", hint: "Uyuma pozisyonu", category: CATEGORIES.ACTIONS },
  { word: "Uyumak", hint: "Gözü kapatma", category: CATEGORIES.ACTIONS },
  { word: "Uyanmak", hint: "Gözü açma", category: CATEGORIES.ACTIONS },
  { word: "Yemek", hint: "Tüketme", category: CATEGORIES.ACTIONS },
  { word: "İçmek", hint: "Sıvı tüketme", category: CATEGORIES.ACTIONS },
  { word: "Konuşmak", hint: "İletişim", category: CATEGORIES.ACTIONS },
  { word: "Dinlemek", hint: "Ses alma", category: CATEGORIES.ACTIONS },
  { word: "Okumak", hint: "Yazı alma", category: CATEGORIES.ACTIONS },
  { word: "Yazmak", hint: "Metin oluşturma", category: CATEGORIES.ACTIONS },
  { word: "Çizmek", hint: "Görsel yaratma", category: CATEGORIES.ACTIONS },
  { word: "Boyamak", hint: "Renk ekleme", category: CATEGORIES.ACTIONS },
  { word: "Şarkı söylemek", hint: "Müzik yapma", category: CATEGORIES.ACTIONS },
  { word: "Dans etmek", hint: "Ritmli hareket", category: CATEGORIES.ACTIONS },
  { word: "Oynamak", hint: "Eğlence", category: CATEGORIES.ACTIONS },
  { word: "Gülmek", hint: "Neşe", category: CATEGORIES.ACTIONS },
  { word: "Ağlamak", hint: "Hüzün", category: CATEGORIES.ACTIONS },
  { word: "Bağırmak", hint: "Öfke", category: CATEGORIES.ACTIONS },
];

const usedWords = new Set<string>();
let currentWordIndex = 0;

function shuffleWords<T>(array: T[]): T[] {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

let shuffledWords = shuffleWords(WORDS);

export function getRandomWord(): Word {
  if (currentWordIndex >= shuffledWords.length) {
    shuffledWords = shuffleWords(WORDS);
    currentWordIndex = 0;
  }
  
  const word = shuffledWords[currentWordIndex];
  currentWordIndex++;
  usedWords.add(word.word);
  return word;
}

export function getCategoryCount(): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const category of Object.values(CATEGORIES)) {
    counts[category] = WORDS.filter(w => w.category === category).length;
  }
  return counts;
}

// Yardımcı fonksiyon: birden fazla kelime döndürür
export function getRandomWords(count: number = 10): Word[] {
  const words = [];
  for (let i = 0; i < count; i++) {
    words.push(getRandomWord());
  }
  return words;
}

// Yardımcı fonksiyon: Belirli bir kategoriden kelime döndürür
export function getRandomWordFromCategory(category: string): Word | null {
  const categoryWords = WORDS.filter(w => w.category === category);
  if (categoryWords.length === 0) return null;
  return categoryWords[Math.floor(Math.random() * categoryWords.length)];
}
